services:
  healthcheck:
    container_name: healthcheck
    build:
      context: ./
      dockerfile: cmd/Dockerfile
    entrypoint: /cmd/healthcheck
    environment:
      - LOGGER_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - health_network

  node1:
    container_name: node1
    build:
      context: ./
      dockerfile: cmd/Dockerfile
    entrypoint: /cmd/health_client
    networks:
      - health_network

  node2:
    container_name: node2
    build:
      context: ./
      dockerfile: cmd/Dockerfile
    entrypoint: /cmd/health_client
    networks:
      - health_network


networks:
  health_network:
    driver: bridge
